title: Valeria N. Mora-Hern√°ndez
description: Spanish Literature Ph.D.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

include:
    - _pages
    - .htaccess
